### ISSUE TITLE
New release on PyPI

### ISSUE THREAD

**Issue by saraedum** [nthiery/recursive-monkey-patch#9]
Do you think you could upload a new release to PyPI? We would like to make https://github.com/MCLF/mclf/pull/79 available on PyPI and recursive-monkey-patch with the latest changes is a dependency :)

**Comment by nthiery** [comment]
Hi!

>    Do you think you could upload a new release to PyPI? We would like to
>    make [1]MCLF/mclf#79 available on PyPI and recursive-monkey-patch with
>    the latest changes is a dependency :)

Sure thing. However I am on vacations until the 14th with little
internet access; can this wait until then? Otherwise let me know which
permission you need to do it, and I'll try to grant them to you.

Cheers,
                                Nicolas

**Comment by saraedum** [comment]
Sure, it can wait.

**Comment by nthiery** [comment]
Done!
